java_test(
    name = "runnerModelTests",
    srcs = glob(["com/google/testing/junit/runner/model/*.java"]),
    tags = ["runner"],
    test_class = "com.google.testing.junit.runner.model.AllTests",
    deps = [
        "//src/java_tools/junitrunner/java/com/google/testing/junit/runner/model",
        "//src/test/java/com/google/devtools/build/lib:testutil",
        "//third_party:junit4",
    ],
)
